// Decompiled with JetBrains decompiler
// Type: DocumentFormat.OpenXml.Spreadsheet.PivotFilterValues
// Assembly: DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: A7316BF1-EDFD-42B4-84FD-A64CEF0DCF01
// Assembly location: C:\Users\graeme smyth\Documents\Visual Studio 2015\Projects\I❤IT\I❤IT\bin\Debug\DocumentFormat.OpenXml.dll

using System.CodeDom.Compiler;

namespace DocumentFormat.OpenXml.Spreadsheet
{
  [GeneratedCode("DomGen", "2.0")]
  public enum PivotFilterValues
  {
    [EnumString("unknown")] Unknown,
    [EnumString("count")] Count,
    [EnumString("percent")] Percent,
    [EnumString("sum")] Sum,
    [EnumString("captionEqual")] CaptionEqual,
    [EnumString("captionNotEqual")] CaptionNotEqual,
    [EnumString("captionBeginsWith")] CaptionBeginsWith,
    [EnumString("captionNotBeginsWith")] CaptionNotBeginsWith,
    [EnumString("captionEndsWith")] CaptionEndsWith,
    [EnumString("captionNotEndsWith")] CaptionNotEndsWith,
    [EnumString("captionContains")] CaptionContains,
    [EnumString("captionNotContains")] CaptionNotContains,
    [EnumString("captionGreaterThan")] CaptionGreaterThan,
    [EnumString("captionGreaterThanOrEqual")] CaptionGreaterThanOrEqual,
    [EnumString("captionLessThan")] CaptionLessThan,
    [EnumString("captionLessThanOrEqual")] CaptionLessThanOrEqual,
    [EnumString("captionBetween")] CaptionBetween,
    [EnumString("captionNotBetween")] CaptionNotBetween,
    [EnumString("valueEqual")] ValueEqual,
    [EnumString("valueNotEqual")] ValueNotEqual,
    [EnumString("valueGreaterThan")] ValueGreaterThan,
    [EnumString("valueGreaterThanOrEqual")] ValueGreaterThanOrEqual,
    [EnumString("valueLessThan")] ValueLessThan,
    [EnumString("valueLessThanOrEqual")] ValueLessThanOrEqual,
    [EnumString("valueBetween")] ValueBetween,
    [EnumString("valueNotBetween")] ValueNotBetween,
    [EnumString("dateEqual")] DateEqual,
    [EnumString("dateNotEqual")] DateNotEqual,
    [EnumString("dateOlderThan")] DateOlderThan,
    [EnumString("dateOlderThanOrEqual")] DateOlderThanOrEqual,
    [EnumString("dateNewerThan")] DateNewerThan,
    [EnumString("dateNewerThanOrEqual")] DateNewerThanOrEqual,
    [EnumString("dateBetween")] DateBetween,
    [EnumString("dateNotBetween")] DateNotBetween,
    [EnumString("tomorrow")] Tomorrow,
    [EnumString("today")] Today,
    [EnumString("yesterday")] Yesterday,
    [EnumString("nextWeek")] NextWeek,
    [EnumString("thisWeek")] ThisWeek,
    [EnumString("lastWeek")] LastWeek,
    [EnumString("nextMonth")] NextMonth,
    [EnumString("thisMonth")] ThisMonth,
    [EnumString("lastMonth")] LastMonth,
    [EnumString("nextQuarter")] NextQuarter,
    [EnumString("thisQuarter")] ThisQuarter,
    [EnumString("lastQuarter")] LastQuarter,
    [EnumString("nextYear")] NextYear,
    [EnumString("thisYear")] ThisYear,
    [EnumString("lastYear")] LastYear,
    [EnumString("yearToDate")] YearToDate,
    [EnumString("Q1")] Quarter1,
    [EnumString("Q2")] Quarter2,
    [EnumString("Q3")] Quarter3,
    [EnumString("Q4")] Quarter4,
    [EnumString("M1")] January,
    [EnumString("M2")] February,
    [EnumString("M3")] March,
    [EnumString("M4")] April,
    [EnumString("M5")] May,
    [EnumString("M6")] June,
    [EnumString("M7")] July,
    [EnumString("M8")] August,
    [EnumString("M9")] September,
    [EnumString("M10")] October,
    [EnumString("M11")] November,
    [EnumString("M12")] December,
  }
}
