// Decompiled with JetBrains decompiler
// Type: DocumentFormat.OpenXml.Drawing.PresetColorValues
// Assembly: DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// MVID: A7316BF1-EDFD-42B4-84FD-A64CEF0DCF01
// Assembly location: C:\Users\graeme smyth\Documents\Visual Studio 2015\Projects\I❤IT\I❤IT\bin\Debug\DocumentFormat.OpenXml.dll

using System.CodeDom.Compiler;

namespace DocumentFormat.OpenXml.Drawing
{
  [GeneratedCode("DomGen", "2.0")]
  public enum PresetColorValues
  {
    [EnumString("aliceBlue")] AliceBlue,
    [EnumString("antiqueWhite")] AntiqueWhite,
    [EnumString("aqua")] Aqua,
    [EnumString("aquamarine")] Aquamarine,
    [EnumString("azure")] Azure,
    [EnumString("beige")] Beige,
    [EnumString("bisque")] Bisque,
    [EnumString("black")] Black,
    [EnumString("blanchedAlmond")] BlanchedAlmond,
    [EnumString("blue")] Blue,
    [EnumString("blueViolet")] BlueViolet,
    [EnumString("brown")] Brown,
    [EnumString("burlyWood")] BurlyWood,
    [EnumString("cadetBlue")] CadetBlue,
    [EnumString("chartreuse")] Chartreuse,
    [EnumString("chocolate")] Chocolate,
    [EnumString("coral")] Coral,
    [EnumString("cornflowerBlue")] CornflowerBlue,
    [EnumString("cornsilk")] Cornsilk,
    [EnumString("crimson")] Crimson,
    [EnumString("cyan")] Cyan,
    [EnumString("dkBlue")] DarkBlue,
    [EnumString("dkCyan")] DarkCyan,
    [EnumString("dkGoldenrod")] DarkGoldenrod,
    [EnumString("dkGray")] DarkGray,
    [EnumString("dkGreen")] DarkGreen,
    [EnumString("dkKhaki")] DarkKhaki,
    [EnumString("dkMagenta")] DarkMagenta,
    [EnumString("dkOliveGreen")] DarkOliveGreen,
    [EnumString("dkOrange")] DarkOrange,
    [EnumString("dkOrchid")] DarkOrchid,
    [EnumString("dkRed")] DarkRed,
    [EnumString("dkSalmon")] DarkSalmon,
    [EnumString("dkSeaGreen")] DarkSeaGreen,
    [EnumString("dkSlateBlue")] DarkSlateBlue,
    [EnumString("dkSlateGray")] DarkSlateGray,
    [EnumString("dkTurquoise")] DarkTurquoise,
    [EnumString("dkViolet")] DarkViolet,
    [EnumString("deepPink")] DeepPink,
    [EnumString("deepSkyBlue")] DeepSkyBlue,
    [EnumString("dimGray")] DimGray,
    [EnumString("dodgerBlue")] DodgerBlue,
    [EnumString("firebrick")] Firebrick,
    [EnumString("floralWhite")] FloralWhite,
    [EnumString("forestGreen")] ForestGreen,
    [EnumString("fuchsia")] Fuchsia,
    [EnumString("gainsboro")] Gainsboro,
    [EnumString("ghostWhite")] GhostWhite,
    [EnumString("gold")] Gold,
    [EnumString("goldenrod")] Goldenrod,
    [EnumString("gray")] Gray,
    [EnumString("green")] Green,
    [EnumString("greenYellow")] GreenYellow,
    [EnumString("honeydew")] Honeydew,
    [EnumString("hotPink")] HotPink,
    [EnumString("indianRed")] IndianRed,
    [EnumString("indigo")] Indigo,
    [EnumString("ivory")] Ivory,
    [EnumString("khaki")] Khaki,
    [EnumString("lavender")] Lavender,
    [EnumString("lavenderBlush")] LavenderBlush,
    [EnumString("lawnGreen")] LawnGreen,
    [EnumString("lemonChiffon")] LemonChiffon,
    [EnumString("ltBlue")] LightBlue,
    [EnumString("ltCoral")] LightCoral,
    [EnumString("ltCyan")] LightCyan,
    [EnumString("ltGoldenrodYellow")] LightGoldenrodYellow,
    [EnumString("ltGray")] LightGray,
    [EnumString("ltGreen")] LightGreen,
    [EnumString("ltPink")] LightPink,
    [EnumString("ltSalmon")] LightSalmon,
    [EnumString("ltSeaGreen")] LightSeaGreen,
    [EnumString("ltSkyBlue")] LightSkyBlue,
    [EnumString("ltSlateGray")] LightSlateGray,
    [EnumString("ltSteelBlue")] LightSteelBlue,
    [EnumString("ltYellow")] LightYellow,
    [EnumString("lime")] Lime,
    [EnumString("limeGreen")] LimeGreen,
    [EnumString("linen")] Linen,
    [EnumString("magenta")] Magenta,
    [EnumString("maroon")] Maroon,
    [EnumString("medAquamarine")] MedAquamarine,
    [EnumString("medBlue")] MediumBlue,
    [EnumString("medOrchid")] MediumOrchid,
    [EnumString("medPurple")] MediumPurple,
    [EnumString("medSeaGreen")] MediumSeaGreen,
    [EnumString("medSlateBlue")] MediumSlateBlue,
    [EnumString("medSpringGreen")] MediumSpringGreen,
    [EnumString("medTurquoise")] MediumTurquoise,
    [EnumString("medVioletRed")] MediumVioletRed,
    [EnumString("midnightBlue")] MidnightBlue,
    [EnumString("mintCream")] MintCream,
    [EnumString("mistyRose")] MistyRose,
    [EnumString("moccasin")] Moccasin,
    [EnumString("navajoWhite")] NavajoWhite,
    [EnumString("navy")] Navy,
    [EnumString("oldLace")] OldLace,
    [EnumString("olive")] Olive,
    [EnumString("oliveDrab")] OliveDrab,
    [EnumString("orange")] Orange,
    [EnumString("orangeRed")] OrangeRed,
    [EnumString("orchid")] Orchid,
    [EnumString("paleGoldenrod")] PaleGoldenrod,
    [EnumString("paleGreen")] PaleGreen,
    [EnumString("paleTurquoise")] PaleTurquoise,
    [EnumString("paleVioletRed")] PaleVioletRed,
    [EnumString("papayaWhip")] PapayaWhip,
    [EnumString("peachPuff")] PeachPuff,
    [EnumString("peru")] Peru,
    [EnumString("pink")] Pink,
    [EnumString("plum")] Plum,
    [EnumString("powderBlue")] PowderBlue,
    [EnumString("purple")] Purple,
    [EnumString("red")] Red,
    [EnumString("rosyBrown")] RosyBrown,
    [EnumString("royalBlue")] RoyalBlue,
    [EnumString("saddleBrown")] SaddleBrown,
    [EnumString("salmon")] Salmon,
    [EnumString("sandyBrown")] SandyBrown,
    [EnumString("seaGreen")] SeaGreen,
    [EnumString("seaShell")] SeaShell,
    [EnumString("sienna")] Sienna,
    [EnumString("silver")] Silver,
    [EnumString("skyBlue")] SkyBlue,
    [EnumString("slateBlue")] SlateBlue,
    [EnumString("slateGray")] SlateGray,
    [EnumString("snow")] Snow,
    [EnumString("springGreen")] SpringGreen,
    [EnumString("steelBlue")] SteelBlue,
    [EnumString("tan")] Tan,
    [EnumString("teal")] Teal,
    [EnumString("thistle")] Thistle,
    [EnumString("tomato")] Tomato,
    [EnumString("turquoise")] Turquoise,
    [EnumString("violet")] Violet,
    [EnumString("wheat")] Wheat,
    [EnumString("white")] White,
    [EnumString("whiteSmoke")] WhiteSmoke,
    [EnumString("yellow")] Yellow,
    [EnumString("yellowGreen")] YellowGreen,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkBlue")] DarkBlue2010,
    [EnumString("darkCyan"), OfficeAvailability(FileFormatVersions.Office2010)] DarkCyan2010,
    [EnumString("darkGoldenrod"), OfficeAvailability(FileFormatVersions.Office2010)] DarkGoldenrod2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkGray")] DarkGray2010,
    [EnumString("darkGrey"), OfficeAvailability(FileFormatVersions.Office2010)] DarkGrey2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkGreen")] DarkGreen2010,
    [EnumString("darkKhaki"), OfficeAvailability(FileFormatVersions.Office2010)] DarkKhaki2010,
    [EnumString("darkMagenta"), OfficeAvailability(FileFormatVersions.Office2010)] DarkMagenta2010,
    [EnumString("darkOliveGreen"), OfficeAvailability(FileFormatVersions.Office2010)] DarkOliveGreen2010,
    [EnumString("darkOrange"), OfficeAvailability(FileFormatVersions.Office2010)] DarkOrange2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkOrchid")] DarkOrchid2010,
    [EnumString("darkRed"), OfficeAvailability(FileFormatVersions.Office2010)] DarkRed2010,
    [EnumString("darkSalmon"), OfficeAvailability(FileFormatVersions.Office2010)] DarkSalmon2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkSeaGreen")] DarkSeaGreen2010,
    [EnumString("darkSlateBlue"), OfficeAvailability(FileFormatVersions.Office2010)] DarkSlateBlue2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkSlateGray")] DarkSlateGray2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkSlateGrey")] DarkSlateGrey2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("darkTurquoise")] DarkTurquoise2010,
    [EnumString("darkViolet"), OfficeAvailability(FileFormatVersions.Office2010)] DarkViolet2010,
    [EnumString("lightBlue"), OfficeAvailability(FileFormatVersions.Office2010)] LightBlue2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightCoral")] LightCoral2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightCyan")] LightCyan2010,
    [EnumString("lightGoldenrodYellow"), OfficeAvailability(FileFormatVersions.Office2010)] LightGoldenrodYellow2010,
    [EnumString("lightGray"), OfficeAvailability(FileFormatVersions.Office2010)] LightGray2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightGrey")] LightGrey2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightGreen")] LightGreen2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightPink")] LightPink2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightSalmon")] LightSalmon2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightSeaGreen")] LightSeaGreen2010,
    [EnumString("lightSkyBlue"), OfficeAvailability(FileFormatVersions.Office2010)] LightSkyBlue2010,
    [EnumString("lightSlateGray"), OfficeAvailability(FileFormatVersions.Office2010)] LightSlateGray2010,
    [EnumString("lightSlateGrey"), OfficeAvailability(FileFormatVersions.Office2010)] LightSlateGrey2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightSteelBlue")] LightSteelBlue2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("lightYellow")] LightYellow2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("mediumAquamarine")] MediumAquamarine2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("mediumBlue")] MediumBlue2010,
    [EnumString("mediumOrchid"), OfficeAvailability(FileFormatVersions.Office2010)] MediumOrchid2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("mediumPurple")] MediumPurple2010,
    [EnumString("mediumSeaGreen"), OfficeAvailability(FileFormatVersions.Office2010)] MediumSeaGreen2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("mediumSlateBlue")] MediumSlateBlue2010,
    [EnumString("mediumSpringGreen"), OfficeAvailability(FileFormatVersions.Office2010)] MediumSpringGreen2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("mediumTurquoise")] MediumTurquoise2010,
    [EnumString("mediumVioletRed"), OfficeAvailability(FileFormatVersions.Office2010)] MediumVioletRed2010,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("dkGrey")] DarkGrey,
    [EnumString("dimGrey"), OfficeAvailability(FileFormatVersions.Office2010)] DimGrey,
    [EnumString("dkSlateGrey"), OfficeAvailability(FileFormatVersions.Office2010)] DarkSlateGrey,
    [EnumString("grey"), OfficeAvailability(FileFormatVersions.Office2010)] Grey,
    [OfficeAvailability(FileFormatVersions.Office2010), EnumString("ltGrey")] LightGrey,
    [EnumString("ltSlateGrey"), OfficeAvailability(FileFormatVersions.Office2010)] LightSlateGrey,
    [EnumString("slateGrey"), OfficeAvailability(FileFormatVersions.Office2010)] SlateGrey,
  }
}
